/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yahtzee;

/**
 *
 * @author sma10
 */
public class RulebookScreen extends javax.swing.JFrame {

    /**
     * Creates new form RulebookScreen
     */
    public RulebookScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ReturnGameButton = new javax.swing.JButton();
        ReturnMainMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yahtzee/RuleImage1.png"))); // NOI18N
        jTabbedPane2.addTab("Page 1", jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yahtzee/RuleImage2.png"))); // NOI18N
        jTabbedPane2.addTab("Page 2", jLabel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yahtzee/RuleImage3.png"))); // NOI18N
        jTabbedPane2.addTab("Page 3", jLabel3);

        ReturnGameButton.setBackground(new java.awt.Color(204, 255, 204));
        ReturnGameButton.setText("Return to previous game");
        ReturnGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnGameButtonActionPerformed(evt);
            }
        });

        ReturnMainMenuButton.setBackground(new java.awt.Color(204, 255, 204));
        ReturnMainMenuButton.setText("Return to Main Menu");
        ReturnMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnMainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReturnGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReturnMainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReturnGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(ReturnMainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnGameButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == ReturnGameButton) {
            this.dispose();
            new TwoPlayerGUI(true).setVisible(true);
            //Jump back to the old game
        }
    }//GEN-LAST:event_ReturnGameButtonActionPerformed

    private void ReturnMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnMainMenuButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == ReturnMainMenuButton) {
            this.dispose();
            new MenuScreen().setVisible(true);
            //Jump back to the old game
        }
    }//GEN-LAST:event_ReturnMainMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnGameButton;
    private javax.swing.JButton ReturnMainMenuButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
